Assignment-2/social-network/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.

find a post 
find its comments
|
*/

// login route

//get
Route::get('user/login', function() {
  return View::make('users.login');
});


//post
Route::post('user/loginUser', 'UserController@loginUser');
Route::post('user/addFriend', 'UserController@addFriend');
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));


// search route

Route::post('user/search', array('as' => 'user.search', 'uses' => 'UserController@search'));
//Route::get('user/search', function() {return View::make('user.search');});


Route::resource('post', 'PostController');
Route::resource('comments', 'CommentController');
Route::resource('user', 'UserController');

// make the home page
//Route::get('/', 'ProductController@index');
Route::get('/', array('as'=>'home','uses'=>'PostController@index'));

Assignment-2/social-network/app/models/Post.php
<?php

class Post extends Eloquent{
    
      
    public static $rules = array(
        'title' => 'required',
        'message' => 'required'
    );
    
    
    function comment(){
        return $this->hasMany('Comment');
    }
    
    function user(){
        return $this->belongsTo('User');
    }
    
}

Assignment-2/social-network/app/controllers/PostController.php
<?php

class PostController extends \BaseController {

	// show the index page
	public function index()
	{

			
			$userId = Auth::id();
		
		
			
			if (Auth::check()){
    			$posts = Auth::user()->post;
    			$username = Auth::user()->name;
    			 
    			return View::make('post.index', compact('posts', 'userId', 'username'));
			}else{
				
				$sql = "SELECT *, users.id AS users_id, count(comments.post_id) AS commentCount FROM users LEFT JOIN posts ON users.id = posts.id LEFT JOIN comments ON posts.id = comments.post_id WHERE privacy='public' group by posts.id ORDER BY posts.id DESC;";
				$publicPosts = DB::select($sql);
				
			return View::make('post.index', compact('publicPosts'));
	
			}
 //$sql = "SELECT *, users.id AS users_id, count(comments.post_id) AS commentCount FROM users LEFT JOIN posts ON users.id = posts.id LEFT JOIN comments ON posts.id = comments.post_id WHERE privacy='public' group by posts.id ORDER BY posts.id DESC;";
//$posts = DB::select($sql);
	
	
	
	
	
	//SELECT * FROM posts LEFT JOIN comments ON posts.id = comments.post_id WHERE posts.privacy = 'private';
	
////	SELECT *, users.id AS users_id FROM users LEFT JOIN posts ON users.id = posts.id WHERE posts.privacy = 'private'
	
	}


	// save a post
	public function store()
	{
		// return form inputs
		$input = Input::all();
		
		// Validation
		$v = Validator::make($input, Post::$rules);
		
		// error check
		if($v->passes()){
		
			// Create new Product
			$posts = new Post();
			
			// assign values
			$posts->title = $input['title'];
			$posts->message = $input['message'];
			$posts->privacy = $input['privacy'];
			$posts->user_id = $input['user_id'];
			
			// save Object
			$posts->save();
			
			// redirect after save
			return Redirect::route('post.index');
		
		} else{
			
			// Pass Validation Object (error msgs)
			return Redirect::action('PostController@index')->withErrors($v);
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
			//$userId = Auth::id();
			$myusers = User::find($id);
			return View::make('post.index')->with('userId', $userId)->with('myusers', $myusers);
	}


	// edit a post
	public function edit($id)
	{
		$post = Post::find($id);
		return View::make('post.edit')->with('post', $post);
	}


	// update a post 
	public function update($id)
	{
		
		// find product to update
		$post = Post::find($id);
		
		$userId = Auth::id();
		
		// return form inputs
		$input = Input::all();
		
		$v = Validator::make($input, Post::$rules);
		
		
		
		// error check
		if($v->passes()){
			
			// assign values
			$post->title = $input['title'];
			$post->message = $input['message'];
			
			// save Object
			$post->save();
			
			// redirect after save
			return Redirect::route('post.index');
			
		} else{
			
			return Redirect::action('PostController@edit', $id)->withInput($input)->withErrors($v);
		
		}
	}


	// delete a post 
	public function destroy($id)
	{
		
		// find product
		$posts = Post::find($id);
		$posts->delete();
		
		// get the comment where the post_id is the id
		$comments = Comment::where('post_id', '=', $id)->get();
		
		// loop through each comment and delete
		foreach($comments as $comment){
			$comment->delete();
		}
		
		// redirect to main page
		return Redirect::route('post.index');
		
	
	}


}

Assignment-2/social-network/app/views/post/create.blade.php
@extends('product.layout')

@section('title')
Do Not need this page
@stop

@section('content')

        <div class="col-sm-1">
           
        </div>


        <div class="col-sm-9">
            
            
             {{ Form::open(array('action' => 'PostController@store')) }}
             <div class="form-group">
                  {{ Form::label('title', 'Post Title: ') }}
                 {{Form::text('title', '', array('class' => 'form-control')) }}
                 {{$errors->first('title')}}
              </div>
              <div class="form-group">
                {{ Form::label('message', 'Message: ') }}
                {{Form::text('message', '', array('class' => 'form-control')) }}
                {{$errors->first('message')}}
               
              </div>
              
              {{ Form::submit('Create', array('class' => 'btn btn-success')) }}
              {{ Form::close() }}
         
        </div>
        
    <div class="col-sm-1">
           
    </div>



@stop

Assignment-2/social-network/app/views/post/edit.blade.php
@extends('post.layout')

@section('title')
Edit
@stop

@section('content')

    <div class="col-sm-1">
           
            
          
    </div>

    <div class="col-sm-9">
        
        <br>
        <br>
        
            {{ Form::model($post, array('method' => 'PUT', 
            'route' => array('post.update', $post->id))) }}

              <div class="form-group">
                  {{ Form::label('title', 'Post Title: ') }}
                 {{Form::text('title', $post->title, array('class' => 'form-control')) }}
                 {{$errors->first('title')}}
              </div>
              <div class="form-group">
                {{ Form::label('message', 'Message: ') }}
                {{Form::text('message', $post->message, array('class' => 'form-control')) }}
                {{$errors->first('message')}}
               
              </div>
              {{ Form::submit('Update', array('class' => 'btn btn-success')) }}
              {{ link_to(URL::previous(), 'Cancel', ['class' => 'btn btn-info']) }}
           
            {{ Form::close() }}
              
          
    </div>
    <div class="col-sm-1">
           
            
          
    </div>



@stop

Assignment-2/social-network/app/views/post/index.blade.php
@extends('post.layout')

@section('title')
Social Network
@stop

 @section('content')

    <div class="row">
    
             @if (Auth::check())
         <div class="col-sm-4">
             
             <div>
        
       
              
                  <p>
                    <strong>Welcome: {{ Auth::user()->name }}</strong>
                    {{ link_to_route('user.edit', 'Edit Profile', array($userId), array('class' => 'btn btn-info')) }}
                    
                  </p> 
                   
               
         
            
            </div>
            
            {{ Form::open(array('action' => 'PostController@store')) }}
            {{ Form::hidden('user_id', $userId) }}
             <div class="form-group">
                  {{ Form::label('title', 'Post Title: ') }}
                 {{Form::text('title', '', array('class' => 'form-control')) }}
                 {{$errors->first('title')}}
              </div>
              <div class="form-group">
                {{ Form::label('message', 'Message: ') }}
                {{Form::text('message', '', array('class' => 'form-control')) }}
                {{$errors->first('message')}}
               
              </div>
              <div class="form-group">
                {{ Form::select('privacy', [
                   'private' => 'Private',
                   'public' => 'Public',
                   'friends' => 'Friends']
                    ) }}
               
              </div>
              {{ Form::submit('Create', array('class' => 'btn btn-success')) }}
              {{ Form::reset('Clear', ['class' => 'btn btn-info']) }}
              {{ Form::close() }}
            
        </div>
        
        @else
            <div class="col-sm-4">
                
            </div>
   
        @endif
    
        <div class="col-sm-8">
        
            <h4>Posts</h4>
            
                 @if (Auth::id())
                 
                          @if ($posts)
                    <ul class="list-group">
                        @foreach ($posts as $post)
                       <li class="list-group-item">
                           @if ($post->commentCount == 1)
                           <span class="badge">{{{ $post->commentCount }}} Comment</span>
                           @else
                            <span class="badge">{{{ $post->commentCount }}} Comments</span>
                            @endif
                           <div class='post'>
                              <img class='post-image' src='images/frog.jpg' alt='photo'>
                              <br>
                              <strong>Title: {{{ $post->title }}} </strong>
                              <br>
                              <strong>
                                 User Name: 
                                </strong> {{{ $username }}}
                             
                              
                              <br>
                              <strong>
                                 Message: 
                                </strong>
                             {{{ $post->message }}}
                              <br>
                              <strong>
                                 Type: 
                                </strong>
                              {{{ $post->privacy }}}
                              <p>
    
                                 
                              </p>
                               
                           </div>
                            <p>
                                {{ Form::open(array('method' => 'DELETE', 'route' => 
                                 array('post.update', $post->id))) }}
                                     {{ link_to_route('post.edit', 'Edit', array($post->id), array('class' => 'btn btn-info')) }}
                                {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                                 {{ link_to_route('comments.show', 'Comments', array($post->id), array('class' => 'btn btn-info')) }}
                                 {{ Form::close() }}
                            <p>
                       </li>
                        @endforeach
                        
                    </ul>
                    @else
                        <p>No items found.</p>
                    @endif
                   
                 @else
                         @foreach ($publicPosts as $publicPost)
                        <ul class="list-group">
                            
                            <li class="list-group-item">
                               @if ($publicPost->commentCount == 0)
                               <span class="badge">{{{ $$publicPost->commentCount }}} Comment</span>
                               @else
                                <span class="badge">{{{ $publicPost->commentCount }}} Comments</span>
                                @endif
                               <div class='post'>
                                  <img class='post-image' src='images/frog.jpg' alt='photo'>
                                  <br>
                                  <strong>Title: {{{ $publicPost->title }}} </strong>
                                  <br>
                                <strong>
                                 User Name: {{{ $publicPost->name }}}
                                </strong> 
                                  <br>
                                  <strong>
                                   Comment: </strong>
                                 {{{ $publicPost->message }}}
                                  <br>
                                  <strong>
                                   Post Type: </strong>
                                  {{{ $publicPost->privacy }}}
                                  <p>
        
                                     
                                  </p>
                                 
                                 
                           </div>
                            <p>
                                {{ Form::open(array('action' => 'PostController@store')) }}
                                    
                                 {{ link_to_route('comments.show', 'Comments', array($publicPost->id), array('class' => 'btn btn-info')) }}
                                 {{ Form::close() }}
                            <p>
                       </li>
                        
                            @endforeach
                            
                        </ul>
                        
   
                @endif
                   
                
        
        </div>
        
    </div>

 
@stop

Assignment-2/social-network/app/views/post/layout.blade.php
<!DOCTYPE html>
<!-- List item. -->
<html>

 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>@yield('title')</title>
    
    <!-- Icon -->
    <link rel="icon" href="{{{ asset('favicon.ico') }}}">
    
    <!-- Custom styles for this template -->
    {{ HTML::style('css/styles.css') }}
    <link rel="stylesheet" href="css/styles.css">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Bootstrap core JavaScript
    ================================================== -->
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  </head>

<body>
  
  <div class="container">  
     
          <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Social Network</a></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              
                <li>
                  <a href="{{ URL::to('./') }}">Home</a>
                </li>
    
                @if (Auth::check())
                <li>
                  <a href="{{{ url("user/logout") }}}" role="button">Logout</a>
                </li>
                <li>
                    
                </li>
                @else
                
                <li>
                  <a href="{{{ url("user/login") }}}">Login</a>
                </li>
                <li>
                  <a href="{{{ url("user/create") }}}">Create User</a>
                  
                </li>
                @endif

            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
            
            <div class="col-lg-4">
              
              </div>
              
           <div class="col-lg-8">
               {{ Form::open(array('route' => array('user.search'))) }}
              <div class="input-group">
                 {{Form::text('query', '', array('placeholder' => 'Search Users...', 'class' => 'form-control')) }}
                  <span class="input-group-btn">
                    {{ Form::submit('Search', array('class' => 'btn btn-default')) }}
                    {{ Form::close() }}
                  </span>
              </div><!-- /input-group -->
            </div><!-- /.col-lg-6 -->
          <br>
          <br>
          <br>
   
           
          @section('content')
          
          
          
          @show
          
  </div> <!-- /container -->
  
</body>
</html>

Assignment-2/social-network/app/views/post/show.blade.php
Form::select('animal', array(
    'Cats' => array('leopard' => 'Leopard'),
    'Dogs' => array('spaniel' => 'Spaniel'),
));